-- ============================================================================
-- Product Recommendation System
-- Automatically recommends products/services via LLM when a career evaluation
-- is inserted or updated with a formatted report.
-- ============================================================================

-- 1. Add recommendation columns to career_evaluations
ALTER TABLE public.career_evaluations
  ADD COLUMN IF NOT EXISTS recommended_product_name TEXT,
  ADD COLUMN IF NOT EXISTS recommendation_description TEXT,
  ADD COLUMN IF NOT EXISTS recommendation_landing_page_url TEXT,
  ADD COLUMN IF NOT EXISTS raw_llm_response JSONB,
  ADD COLUMN IF NOT EXISTS recommendation_status TEXT DEFAULT 'pending'
    CHECK (recommendation_status IN ('pending', 'processing', 'completed', 'error', 'skipped'));

COMMENT ON COLUMN public.career_evaluations.recommended_product_name IS 'Name of the LLM-recommended service from hub_services';
COMMENT ON COLUMN public.career_evaluations.recommendation_description IS 'Personalized description generated by LLM explaining why this service fits the lead';
COMMENT ON COLUMN public.career_evaluations.recommendation_landing_page_url IS 'Landing page URL from the matched hub_service';
COMMENT ON COLUMN public.career_evaluations.raw_llm_response IS 'Full raw JSON response from the LLM for audit/debugging';
COMMENT ON COLUMN public.career_evaluations.recommendation_status IS 'Status of the recommendation pipeline: pending, processing, completed, error, skipped';

-- 2. Backfill existing completed reports as skipped (they predate this system)
UPDATE public.career_evaluations
SET recommendation_status = 'skipped'
WHERE formatted_report IS NOT NULL
  AND recommendation_status = 'pending';

-- 3. Add admin-configurable prompt to app_configs
INSERT INTO app_configs (key, value, description) VALUES
  ('llm_product_recommendation_prompt',
   E'Você é um especialista em recomendação de produtos educacionais.\n\nDados do lead: {{lead_data}}\nTier recomendado: {{tier}}\nServiços disponíveis: {{services}}\n\nCom base no tier e no perfil do lead, recomende o serviço mais adequado da lista acima.\nRetorne um JSON com:\n- recommended_service_name: nome exato do serviço conforme cadastrado\n- recommendation_description: 1 a 2 parágrafos explicando como esse serviço ajuda o lead a atingir o objetivo dele, de forma personalizada\n- justification: motivo técnico da escolha com base no tier e perfil\n\nRetorne apenas o JSON, sem texto adicional.',
   'Prompt usado pela IA para recomendar produtos/serviços aos leads. Variáveis: {{lead_data}}, {{tier}}, {{services}}')
ON CONFLICT (key) DO NOTHING;

-- 4. Trigger function: calls recommend-product edge function via pg_net
CREATE OR REPLACE FUNCTION trigger_recommend_product()
RETURNS TRIGGER AS $$
DECLARE
  edge_url TEXT;
  anon_key TEXT;
  request_id BIGINT;
  report_json JSONB;
  tier TEXT;
BEGIN
  -- Read edge function config
  SELECT value INTO edge_url FROM app_configs WHERE key = 'supabase_edge_url';
  SELECT value INTO anon_key FROM app_configs WHERE key = 'supabase_anon_key';

  IF edge_url IS NULL OR anon_key IS NULL THEN
    RAISE WARNING '[recommend-product] Missing supabase_edge_url or supabase_anon_key in app_configs - skipping';
    RETURN NEW;
  END IF;

  -- Quick-check: try to extract tier from formatted_report JSON
  BEGIN
    report_json := NEW.formatted_report::JSONB;
    tier := report_json -> 'product_recommendation' -> 'primary_offer' ->> 'recommended_product_tier';
  EXCEPTION
    WHEN OTHERS THEN
      tier := NULL;
  END;

  -- If no tier found, also check lead_qualification path
  IF tier IS NULL THEN
    BEGIN
      tier := report_json -> 'lead_qualification' ->> 'recommended_product_tier';
    EXCEPTION
      WHEN OTHERS THEN
        tier := NULL;
    END;
  END IF;

  IF tier IS NULL OR tier = '' THEN
    RAISE NOTICE '[recommend-product] No recommended_product_tier found for evaluation % - skipping', NEW.id;
    -- Mark as skipped directly to avoid unnecessary edge function call
    UPDATE public.career_evaluations
    SET recommendation_status = 'skipped'
    WHERE id = NEW.id;
    RETURN NEW;
  END IF;

  -- Fire-and-forget: call the edge function via pg_net
  SELECT INTO request_id net.http_post(
    url := edge_url || '/recommend-product',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || anon_key,
      'apikey', anon_key
    ),
    body := jsonb_build_object('evaluationId', NEW.id::text)
  );

  RAISE NOTICE '[recommend-product] Triggered for evaluation % (tier: %, request_id: %)', NEW.id, tier, request_id;
  RETURN NEW;

EXCEPTION
  WHEN OTHERS THEN
    RAISE WARNING '[recommend-product] Failed to trigger for %: %', NEW.id, SQLERRM;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Create trigger
-- Fires AFTER INSERT OR UPDATE OF formatted_report
-- WHEN clause prevents recursion: only fires when formatted_report exists
-- and recommendation hasn't started yet
DROP TRIGGER IF EXISTS trigger_recommend_product_on_report ON public.career_evaluations;

CREATE TRIGGER trigger_recommend_product_on_report
  AFTER INSERT OR UPDATE OF formatted_report
  ON public.career_evaluations
  FOR EACH ROW
  WHEN (
    NEW.formatted_report IS NOT NULL
    AND (NEW.recommendation_status IS NULL OR NEW.recommendation_status = 'pending')
  )
  EXECUTE FUNCTION trigger_recommend_product();

-- 6. Permissions
GRANT EXECUTE ON FUNCTION trigger_recommend_product() TO postgres, service_role;

COMMENT ON FUNCTION trigger_recommend_product() IS
  'Automatically triggers product recommendation via LLM when a career evaluation has a formatted report with a product tier';
COMMENT ON TRIGGER trigger_recommend_product_on_report ON public.career_evaluations IS
  'Fires recommend-product edge function when formatted_report is set and recommendation is pending';
