-- =============================================
-- Seed Campaign Email Templates
-- All templates include {{trackingPixel}} and {{unsubscribeLink}} variables
-- Admin can edit content via Unlayer editor later
-- =============================================

INSERT INTO public.email_templates (name, display_name, subject, body_html, variables, category, description, enabled)
VALUES

-- DRIP: Report completion sequence
('drip_report_d0', 'Drip D0 - Resultado Pronto', 'Seu diagnóstico de carreira está pronto! 🎯', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">{{leadName}}, seu diagnóstico está pronto!</h1><p>Analisamos suas respostas e preparamos um relatório personalizado sobre sua jornada profissional para os EUA.</p><p><a href="{{reportLink}}" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Ver Meu Diagnóstico</a></p><p style="color:#64748b;font-size:14px;margin-top:32px">Dentro do relatório você encontrará: sua pontuação de prontidão, análise detalhada por dimensão, plano de ação personalizado e próximos passos recomendados.</p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{leadName}}","{{reportLink}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Dia 0 do drip pós-diagnóstico — link para o relatório', true),

('drip_report_d3', 'Drip D3 - Dicas Baseadas no Diagnóstico', '3 dicas personalizadas baseadas no seu diagnóstico', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">{{leadName}}, 3 dicas para acelerar sua jornada</h1><p>Com base no seu diagnóstico, separamos 3 ações rápidas que podem fazer diferença imediata:</p><ol style="line-height:2"><li><strong>Revise seu currículo no formato americano</strong> — o formato brasileiro não funciona nos EUA</li><li><strong>Traduza seus títulos profissionais</strong> — usar o título correto multiplica suas chances</li><li><strong>Identifique empresas que patrocinam visto</strong> — nem todas patrocinam, foque nas certas</li></ol><p>Quer ajuda com essas ações? Nossa plataforma automatiza todas elas.</p><p><a href="https://hub.euanapratica.com/assinar" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Conhecer a Plataforma</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{leadName}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Dia 3 do drip — dicas de valor', true),

('drip_report_d7', 'Drip D7 - Plano de Ação', 'Você viu o plano de ação no seu diagnóstico?', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">{{leadName}}, não deixe seu plano de ação parado</h1><p>Faz uma semana que seu diagnóstico ficou pronto. Dentro dele há um plano de ação personalizado com etapas para os próximos 30, 90 e 180 dias.</p><p>Já começou a implementar? Se precisar de orientação, uma sessão de consultoria pode ajudar a priorizar os próximos passos.</p><p><a href="{{reportLink}}" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Rever Meu Diagnóstico</a></p><p style="margin-top:16px"><a href="https://hub.euanapratica.com/consultoria" style="color:#2563eb;font-weight:600">Agendar Consultoria →</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{leadName}}","{{reportLink}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Dia 7 do drip — plano de ação', true),

('drip_report_d14', 'Drip D14 - Última Chance', 'Última chance: sua consultoria com desconto', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">{{leadName}}, última oportunidade</h1><p>Já se passaram 2 semanas desde seu diagnóstico. Muitos dos nossos alunos que estavam na mesma situação que você já deram o próximo passo.</p><p>Que tal uma sessão de consultoria para desenhar sua estratégia personalizada?</p><p><a href="https://hub.euanapratica.com/consultoria" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Agendar Consultoria</a></p><p style="margin-top:16px">Ou, se preferir ferramentas de autoatendimento:</p><p><a href="https://hub.euanapratica.com/assinar" style="color:#2563eb;font-weight:600">Ver Planos da Plataforma →</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{leadName}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Dia 14 do drip — oferta final', true),

-- SINGLE STEP: Leads quentes
('lead_hot_no_conversion', 'Lead Quente - Oferta', '{{leadName}}, você tem grande potencial para os EUA', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">{{leadName}}, seu perfil se destaca!</h1><p>Analisamos seu diagnóstico e identificamos que você tem um potencial acima da média para uma transição profissional para os EUA.</p><p>Profissionais com perfis similares ao seu que usaram nossa plataforma conseguiram resultados em 3 a 6 meses.</p><p>Que tal dar o próximo passo?</p><p><a href="https://hub.euanapratica.com/assinar" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Começar Agora</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{leadName}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Email para leads quentes/muito-quentes sem conversão', true),

-- SINGLE STEP: Upgrade nudge
('upgrade_nudge_credits', 'Upgrade Nudge - Créditos Esgotados', 'Seus créditos acabaram — desbloqueie mais!', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">{{recipientName}}, seus créditos do mês acabaram</h1><p>Você usou todos os créditos disponíveis no seu plano atual. Isso é ótimo — significa que você está usando a plataforma!</p><p>Para continuar usando nossas ferramentas de IA sem esperar o próximo ciclo, considere fazer upgrade:</p><ul style="line-height:2"><li><strong>Pro</strong> — 30 créditos/mês + relatório completo + mentoria</li><li><strong>VIP</strong> — créditos ilimitados + acesso total + prioridade</li></ul><p><a href="https://hub.euanapratica.com/assinar" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Fazer Upgrade</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{recipientName}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Nudge quando créditos unificados esgotam', true),

-- SINGLE STEP: Assinante inativo
('subscriber_inactive', 'Assinante Inativo - Reativação', '{{userName}}, sentimos sua falta na plataforma!', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">{{userName}}, faz tempo que não te vemos!</h1><p>Percebemos que você não usa a plataforma há {{inactiveDays}} dias. Temos novidades que podem te interessar:</p><ul style="line-height:2"><li>Novas vagas no Prime Jobs atualizadas semanalmente</li><li>Melhorias no ResumePass AI para currículos ainda melhores</li><li>Novos horários de mentoria disponíveis</li></ul><p>Seu plano <strong>{{planName}}</strong> está ativo e seus créditos estão esperando por você!</p><p><a href="https://hub.euanapratica.com/dashboard" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Voltar à Plataforma</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{userName}}","{{planName}}","{{inactiveDays}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Reativação de assinantes inativos', true),

-- DRIP: Onboarding assinante
('onboarding_sub_d1', 'Onboarding D1 - Boas-vindas', 'Bem-vindo ao {{planName}}! Comece por aqui 🚀', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">Bem-vindo, {{recipientName}}!</h1><p>Sua assinatura <strong>{{planName}}</strong> está ativa. Aqui está como aproveitar ao máximo:</p><ol style="line-height:2"><li><strong>ResumePass AI</strong> — Adapte seu currículo para o mercado americano</li><li><strong>Title Translator</strong> — Traduza seus títulos profissionais</li><li><strong>Prime Jobs</strong> — Encontre vagas que patrocinam visto</li></ol><p><a href="https://hub.euanapratica.com/dashboard" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Começar Agora</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{recipientName}}","{{planName}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Dia 1 do onboarding de assinante', true),

('onboarding_sub_d3', 'Onboarding D3 - Primeira Feature', '{{recipientName}}, já usou o ResumePass AI?', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">Já experimentou o ResumePass AI?</h1><p>{{recipientName}}, a ferramenta mais popular entre nossos assinantes é o ResumePass AI. Ele analisa seu currículo e sugere melhorias específicas para o mercado americano.</p><p>Em média, nossos usuários aumentam a taxa de resposta em 3x após otimizar o currículo.</p><p><a href="https://hub.euanapratica.com/curriculo" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Otimizar Meu Currículo</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{recipientName}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Dia 3 do onboarding — incentivo ao uso', true),

('onboarding_sub_d7', 'Onboarding D7 - Comunidade', '{{recipientName}}, dica da semana + comunidade', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">Uma semana de assinante!</h1><p>{{recipientName}}, completou uma semana com a gente! Aqui vai uma dica valiosa:</p><p style="background:#f1f5f9;padding:16px;border-radius:8px;border-left:4px solid #2563eb"><strong>Dica:</strong> Agende uma mentoria para revisar sua estratégia. Nossos mentores já ajudaram centenas de profissionais a fazer a transição.</p><p><a href="https://hub.euanapratica.com/agendar" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Agendar Mentoria</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{recipientName}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Dia 7 do onboarding — comunidade e mentoria', true),

-- SINGLE STEP: Win-back
('winback_30d', 'Win-back 30 dias', '{{userName}}, queremos você de volta!', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">{{userName}}, sentimos sua falta!</h1><p>Faz 30 dias que você cancelou sua assinatura. Desde então, adicionamos diversas melhorias:</p><ul style="line-height:2"><li>Novas ferramentas de IA para preparação de entrevistas</li><li>Mais vagas atualizadas semanalmente</li><li>Horários flexíveis de mentoria</li></ul><p>Que tal voltar e continuar sua jornada?</p><p><a href="https://hub.euanapratica.com/assinar" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Reativar Assinatura</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{userName}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Win-back 30 dias após cancelamento', true),

-- SINGLE STEP: Lead frio reengajamento
('lead_cold_reengagement', 'Reengajamento Lead Frio', '{{leadName}}, seu diagnóstico ainda está disponível', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">{{leadName}}, seu diagnóstico continua disponível</h1><p>Faz um tempo que você completou seu diagnóstico de carreira para os EUA. Seu relatório personalizado continua disponível e pode ser acessado a qualquer momento.</p><p>O mercado de trabalho nos EUA está em constante mudança. Que tal rever suas opções?</p><p><a href="{{reportLink}}" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Rever Meu Diagnóstico</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{leadName}}","{{reportLink}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Reengajamento de leads frios (30+ dias)', true),

-- SINGLE STEP: Follow-up pos-consultoria
('followup_post_booking', 'Follow-up Pós-Consultoria', '{{userName}}, como foi sua consultoria?', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">Como foi sua consultoria?</h1><p>{{userName}}, esperamos que sua sessão tenha sido produtiva! Para dar continuidade ao que foi discutido, que tal contar com nossas ferramentas no dia a dia?</p><p>Com uma assinatura você tem acesso a:</p><ul style="line-height:2"><li>ResumePass AI para otimizar seu currículo</li><li>Prime Jobs com vagas que patrocinam visto</li><li>Mais sessões de mentoria</li></ul><p><a href="https://hub.euanapratica.com/assinar" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Ver Planos</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{userName}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Follow-up 24h após consultoria concluída', true),

-- SINGLE STEP: Milestone de uso
('usage_milestone', 'Milestone de Uso', 'Parabéns, {{recipientName}}! 🎉 Você atingiu {{milestone}} usos', '<html><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;max-width:600px;margin:0 auto;padding:20px;color:#334155"><h1 style="color:#1e40af">Parabéns, {{recipientName}}! 🎉</h1><p>Você atingiu <strong>{{milestone}} usos</strong> das nossas ferramentas! Isso mostra dedicação com sua jornada profissional.</p><p>Continue assim — cada uso te aproxima mais do seu objetivo de trabalhar nos EUA.</p><p><a href="https://hub.euanapratica.com/dashboard" style="display:inline-block;background:#2563eb;color:white;padding:12px 24px;border-radius:8px;text-decoration:none;font-weight:600">Continuar Usando</a></p>{{trackingPixel}}<hr style="border:none;border-top:1px solid #e2e8f0;margin:32px 0"><p style="font-size:12px;color:#94a3b8;text-align:center"><a href="{{unsubscribeLink}}" style="color:#94a3b8">Cancelar inscrição</a></p></body></html>', '["{{recipientName}}","{{milestone}}","{{trackingPixel}}","{{unsubscribeLink}}"]'::JSONB, 'campaign', 'Celebração de marcos de uso (5, 10, 25)', true)

ON CONFLICT (name) DO NOTHING;
