-- =============================================
-- Standardize drip email templates to use the same
-- gradient banner layout as report_ready template
-- =============================================

-- D0 - Resultado Pronto
UPDATE public.email_templates
SET body_html = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#1e3a5f,#2563eb);padding:30px;text-align:center;"><h1 style="color:#ffffff;margin:0;font-size:24px;">Seu Diagnostico Esta Pronto!</h1></td></tr><tr><td style="padding:30px;"><h2 style="color:#1e3a5f;margin-top:0;">Ola {{leadName}}!</h2><p style="color:#333;font-size:16px;line-height:1.6;">Analisamos suas respostas e preparamos um relatorio personalizado sobre sua jornada profissional para os EUA.</p><p style="text-align:center;margin:30px 0;"><a href="{{reportLink}}" style="background-color:#2563eb;color:#ffffff;padding:14px 28px;text-decoration:none;border-radius:8px;font-size:16px;font-weight:bold;display:inline-block;">Acessar Meu Diagnostico</a></p><p style="color:#333;font-size:16px;line-height:1.6;">O relatorio inclui:</p><ul style="color:#333;font-size:16px;line-height:1.8;"><li>Sua fase atual na Rota EUA</li><li>Score de prontidao internacional</li><li>Plano de acao personalizado</li><li>Recomendacoes de proximos passos</li></ul><p style="color:#666;font-size:14px;margin-top:30px;">Abraco,<br><strong>Equipe EUA na Pratica</strong></p></td></tr><tr><td style="background-color:#f8f9fa;padding:20px;text-align:center;"><p style="color:#999;font-size:12px;margin:0;">EUA na Pratica. Todos os direitos reservados.</p><p style="margin:8px 0 0;"><a href="{{unsubscribeLink}}" style="color:#999;font-size:12px;">Cancelar inscricao</a></p></td></tr></table></td></tr></table>{{trackingPixel}}</body></html>'
WHERE name = 'drip_report_d0';

-- D3 - Dicas Baseadas no Diagnostico
UPDATE public.email_templates
SET body_html = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#1e3a5f,#2563eb);padding:30px;text-align:center;"><h1 style="color:#ffffff;margin:0;font-size:24px;">3 Dicas Para Acelerar Sua Jornada</h1></td></tr><tr><td style="padding:30px;"><h2 style="color:#1e3a5f;margin-top:0;">Ola {{leadName}}!</h2><p style="color:#333;font-size:16px;line-height:1.6;">Com base no seu diagnostico, separamos 3 acoes rapidas que podem fazer diferenca imediata:</p><ol style="color:#333;font-size:16px;line-height:2;"><li><strong>Revise seu curriculo no formato americano</strong> — o formato brasileiro nao funciona nos EUA</li><li><strong>Traduza seus titulos profissionais</strong> — usar o titulo correto multiplica suas chances</li><li><strong>Identifique empresas que patrocinam visto</strong> — nem todas patrocinam, foque nas certas</li></ol><p style="color:#333;font-size:16px;line-height:1.6;">Quer ajuda com essas acoes? Nossa plataforma automatiza todas elas.</p><p style="text-align:center;margin:30px 0;"><a href="https://hub.euanapratica.com/assinar" style="background-color:#2563eb;color:#ffffff;padding:14px 28px;text-decoration:none;border-radius:8px;font-size:16px;font-weight:bold;display:inline-block;">Conhecer a Plataforma</a></p><p style="color:#666;font-size:14px;margin-top:30px;">Abraco,<br><strong>Equipe EUA na Pratica</strong></p></td></tr><tr><td style="background-color:#f8f9fa;padding:20px;text-align:center;"><p style="color:#999;font-size:12px;margin:0;">EUA na Pratica. Todos os direitos reservados.</p><p style="margin:8px 0 0;"><a href="{{unsubscribeLink}}" style="color:#999;font-size:12px;">Cancelar inscricao</a></p></td></tr></table></td></tr></table>{{trackingPixel}}</body></html>'
WHERE name = 'drip_report_d3';

-- D7 - Plano de Acao
UPDATE public.email_templates
SET body_html = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#1e3a5f,#2563eb);padding:30px;text-align:center;"><h1 style="color:#ffffff;margin:0;font-size:24px;">Seu Plano de Acao Personalizado</h1></td></tr><tr><td style="padding:30px;"><h2 style="color:#1e3a5f;margin-top:0;">{{leadName}}, nao deixe seu plano parado!</h2><p style="color:#333;font-size:16px;line-height:1.6;">Faz uma semana que seu diagnostico ficou pronto. Dentro dele ha um plano de acao personalizado com etapas para os proximos 30, 90 e 180 dias.</p><p style="color:#333;font-size:16px;line-height:1.6;">Ja comecou a implementar? Se precisar de orientacao, uma sessao de consultoria pode ajudar a priorizar os proximos passos.</p><p style="text-align:center;margin:30px 0;"><a href="{{reportLink}}" style="background-color:#2563eb;color:#ffffff;padding:14px 28px;text-decoration:none;border-radius:8px;font-size:16px;font-weight:bold;display:inline-block;">Rever Meu Diagnostico</a></p><p style="text-align:center;"><a href="https://hub.euanapratica.com/consultoria" style="color:#2563eb;font-size:16px;font-weight:600;text-decoration:none;">Agendar Consultoria &rarr;</a></p><p style="color:#666;font-size:14px;margin-top:30px;">Abraco,<br><strong>Equipe EUA na Pratica</strong></p></td></tr><tr><td style="background-color:#f8f9fa;padding:20px;text-align:center;"><p style="color:#999;font-size:12px;margin:0;">EUA na Pratica. Todos os direitos reservados.</p><p style="margin:8px 0 0;"><a href="{{unsubscribeLink}}" style="color:#999;font-size:12px;">Cancelar inscricao</a></p></td></tr></table></td></tr></table>{{trackingPixel}}</body></html>'
WHERE name = 'drip_report_d7';

-- D14 - Ultima Chance
UPDATE public.email_templates
SET body_html = '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;font-family:Arial,Helvetica,sans-serif;background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff;border-radius:8px;overflow:hidden;"><tr><td style="background:linear-gradient(135deg,#1e3a5f,#2563eb);padding:30px;text-align:center;"><h1 style="color:#ffffff;margin:0;font-size:24px;">Ultima Oportunidade</h1></td></tr><tr><td style="padding:30px;"><h2 style="color:#1e3a5f;margin-top:0;">{{leadName}}, nao perca essa chance!</h2><p style="color:#333;font-size:16px;line-height:1.6;">Ja se passaram 2 semanas desde seu diagnostico. Muitos dos nossos alunos que estavam na mesma situacao que voce ja deram o proximo passo.</p><p style="color:#333;font-size:16px;line-height:1.6;">Que tal uma sessao de consultoria para desenhar sua estrategia personalizada?</p><p style="text-align:center;margin:30px 0;"><a href="https://hub.euanapratica.com/consultoria" style="background-color:#2563eb;color:#ffffff;padding:14px 28px;text-decoration:none;border-radius:8px;font-size:16px;font-weight:bold;display:inline-block;">Agendar Consultoria</a></p><p style="color:#333;font-size:16px;line-height:1.6;">Ou, se preferir ferramentas de autoatendimento:</p><p style="text-align:center;"><a href="https://hub.euanapratica.com/servicos/rota60min" style="color:#2563eb;font-size:16px;font-weight:600;text-decoration:none;">Conhecer a Rota 60min &rarr;</a></p><p style="color:#666;font-size:14px;margin-top:30px;">Abraco,<br><strong>Equipe EUA na Pratica</strong></p></td></tr><tr><td style="background-color:#f8f9fa;padding:20px;text-align:center;"><p style="color:#999;font-size:12px;margin:0;">EUA na Pratica. Todos os direitos reservados.</p><p style="margin:8px 0 0;"><a href="{{unsubscribeLink}}" style="color:#999;font-size:12px;">Cancelar inscricao</a></p></td></tr></table></td></tr></table>{{trackingPixel}}</body></html>'
WHERE name = 'drip_report_d14';
